### ISSUE TITLE
Forge and Aetherium Prism Structure

### ISSUE THREAD

**Issue by UnpeelableBanana** [Ender-Development/Aetherworks-Extended-Life#1]
Both structures do not change texture when activated. They do not have the red runes on the side for the forge and the blue runes on the aetherium prism structure.

**Comment by MasterEnderman** [comment]
Interesting I didn't made any code changes except, implementing everything I did before via mixins.

**Comment by MasterEnderman** [comment]
![image](https://github.com/Ender-Development/Aetherworks-Extended-Life/assets/24524662/7a8c9d4c-29cd-4de6-8c3b-4bda25ec2a45)
 I'm unable to reproduce the issue. Both structures can be formed in my fork.
