### ISSUE TITLE
Aetherium Forge crashes instead of crafting

### ISSUE THREAD

**Issue by Sandman366** [Ender-Development/Aetherworks-Extended-Life#3]
Had an issue in a modpack with this, figured I'd try a barebones setup first to check it wasn't part of the pack. Aetherworks unofficial 1.1.0, Embers extended life 1.23.6, JEI (HEI), and mixinbooter I guess was a dependency for something since it added itself. Bare minimum, except for JEI to grab items easier. Build forge base, place core, add fluid, add ingot, start heating....when it reaches 2100 heat, instead of however the process is meant to work for making an Aetherium ingot, it crashes. Constant crash, too, re-loading re-crashes when trying to load the world.

![image](https://github.com/Ender-Development/Aetherworks-Extended-Life/assets/47545215/2b591ab9-a01c-46c5-8b8a-296517817c3b)
(heaters off so I can make sure I actually get my picture proof of setup instead of worrying about it crashing again)
[crash-2024-06-23_08.48.47-server.txt](https://github.com/user-attachments/files/15944738/crash-2024-06-23_08.48.47-server.txt)

**Comment by MasterEnderman** [comment]
Thanks for the report. IIRC I encountered a similar issue before. Guess I have to do some research to find it again.

**Comment by Sandman366** [comment]
Just checked making Aetherium Gems, looks like same problem. Probably same root cause, at least.

**Comment by MasterEnderman** [comment]
Yeah it's related to the refactoring I did in my Embers fork.

`java.lang.ClassCastException: v0id.aw.common.tile.SyncableEmberCapacity cannot be cast to teamroots.embers.power.IEmberCapability`

It should crash with any aetherworks block that tries to implement "SyncableEmberCapacity".
